title: "💡 Feature Request: "
labels: [Feature Request]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request! 🙏
  - type: checkboxes
    id: feature-category
    validations:
      required: true
    attributes:
      label: "Does your feature request fit any of these categories"
      description: "Marking a category helps us to track your requests"
      options:
        - label: "Items" 
        - label: "Dungeons"
        - label: "Achievements"
        - label: "Tasks"
        - label: "Sides"
        - label: "Quests"
        - label: "Pets"
        - label: "Party"
        - label: "Npc"
        - label: "Market"
        - label: "Location"
        - label: "Level"
        - label: "Guilds"
        - label: "Battles"
        - label: "Admin"
        - label: "Other"
          
  - type: textarea
    id: new-feature
    validations:
      required: false
    attributes:
      label: "Is your feature a new and non-existing feature the bot doesn't have?"
      description: "Please describe it!"
      placeholder: "Can we add..."
          
  - type: textarea
    id: problem-related
    validations:
      required: false
    attributes:
      label: "Is your feature request related to a problem?"
      description: "Please describe it!"
      placeholder: " I'm always frustrated when ..."
      
  - type: textarea
    id: considered-alternatives
    validations:
      required: false
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "Instead of A, I've tried B ..."
  - type: textarea
    id: additional-context
    attributes:
      label: "📝 Additional context"
      description: Is there any other context for the feature request?
