name: "💡 Feature Requestt"
description: "Submit a feature request to help us improve"
title: "💡 Feature Request: "
labels: [Feature Request]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request! 🙏
  - type: textarea+
    id: problem-related
    validations:
      required: false
    attributes:
      label: "Is your feature request related to a problem?"
      description: "Please describe it!"
      placeholder: " I'm always frustrated when ..."
  - type: textarea
    id: considered-alternatives
    validations:
      required: false
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "Instead of A, I've tried B ..."
  - type: textarea
    id: additional-context
    attributes:
      label: "📝 Additional context"
      description: Is there any other context for the feature request?